## Numpy Library
https://www.w3schools.com/python/numpy/numpy_random.asp

In [1]:
import numpy as np

#### Numpy Array

In [87]:
a=np.array([[1,2,1],[1,2,3],[3,2,1]])
a

array([[1, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [95]:
a[:2, ::2] # Array with first 2 rows and alternate columns(0 and 2)

array([[1, 1],
       [1, 3]])

In [98]:
a[2]

array([3, 2, 1])

In [92]:
a>2

array([[False, False, False],
       [False, False,  True],
       [ True, False, False]])

In [93]:
a[a>2]

array([3, 3])

In [107]:
np.random.randint(1,55) # gives only `one value` like random module

31

In [104]:
a=np.random.rand(4,5) #4x5 is the matrix shape
a

array([[0.05270999, 0.23543134, 0.45630039, 0.89640887, 0.7753944 ],
       [0.77620289, 0.51939976, 0.00533486, 0.86210133, 0.00422643],
       [0.99103707, 0.662824  , 0.38728256, 0.82816381, 0.91020253],
       [0.73696301, 0.16635425, 0.13319199, 0.48219759, 0.06955559]])

In [31]:
a= a.reshape(10,2)
a

array([[0.68171843, 0.90251258],
       [0.39423143, 0.73695287],
       [0.30820204, 0.88449487],
       [0.24044494, 0.16951156],
       [0.04970543, 0.71377082],
       [0.23757688, 0.55200488],
       [0.22359415, 0.83469023],
       [0.14050871, 0.341797  ],
       [0.77235724, 0.02519005],
       [0.59259048, 0.63325167]])

#### Shape, Size & Dimension

In [32]:
a.shape

(10, 2)

In [105]:
a.size

20

In [33]:
a.ndim #Dimension of the array

2

#### Reshaping a Matrix

In [43]:
a1=a.reshape(1,1,5,4) #number of times 1 is repeated increases the dimension 
a1

array([[[[0.68171843, 0.90251258, 0.39423143, 0.73695287],
         [0.30820204, 0.88449487, 0.24044494, 0.16951156],
         [0.04970543, 0.71377082, 0.23757688, 0.55200488],
         [0.22359415, 0.83469023, 0.14050871, 0.341797  ],
         [0.77235724, 0.02519005, 0.59259048, 0.63325167]]]])

In [42]:
a1.ndim

4

#### Multiplication of a Matrix

In [46]:
a2=np.array([[1,2,3],[1,2,3],[1,2,3]])
a3=np.array([[1,2,3],[1,2,3],[1,2,3]])
a2*a3 # this is item multiplication but `not matrix` multiplication

array([[1, 4, 9],
       [1, 4, 9],
       [1, 4, 9]])

In [47]:
a2@a3 #matrix multiplication

array([[ 6, 12, 18],
       [ 6, 12, 18],
       [ 6, 12, 18]])

In [49]:
np.matmul(a2,a3) #another way for matrix muliplication (matmul function)

array([[ 6, 12, 18],
       [ 6, 12, 18],
       [ 6, 12, 18]])

In [102]:
a2.dot(a3)  # matrix multiplication (dot function)

array([[ 6, 12, 18],
       [ 6, 12, 18],
       [ 6, 12, 18]])

In [50]:
a2/0

C:\Users\ADNAN\AppData\Local\Temp/ipykernel_8864/1664676690.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a2/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [51]:
a2*2

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [100]:
a2**3

array([[ 1,  8, 27],
       [ 1,  8, 27],
       [ 1,  8, 27]], dtype=int32)

#### Zeros, Ones and Full Matrix

In [55]:
zero=np.zeros((4,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
one=np.ones((5,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
zero+11

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [84]:
np.full((4,4),  6, dtype='int') #first arg is `dim` and second arg is `data` and third is `type`

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [85]:
np.full((4,4),  10, dtype='int')

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

#### Broadcasting Operation

In [59]:
one+np.array([1,2,3,4,5]) # row must be kept same

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [60]:
one+np.array([2,3,4,4]) # here row is not same

ValueError: operands could not be broadcast together with shapes (5,5) (4,) 

### Transpose

In [62]:
a2.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

#### Aggregate Functions (Universal Function)

In [63]:
np.sqrt(a2)

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [64]:
np.log10(a2)

array([[0.        , 0.30103   , 0.47712125],
       [0.        , 0.30103   , 0.47712125],
       [0.        , 0.30103   , 0.47712125]])

In [65]:
np.exp(a2)

array([[ 2.71828183,  7.3890561 , 20.08553692],
       [ 2.71828183,  7.3890561 , 20.08553692],
       [ 2.71828183,  7.3890561 , 20.08553692]])

In [66]:
np.mean(a2)

2.0

### arange(), linspace() & logspace()

In [70]:
list(range(2,10,0.1)) # here step is always a natural number

TypeError: 'float' object cannot be interpreted as an integer

In [68]:
np.arange(2,10,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
       7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
       8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
       9.8, 9.9])

In [73]:
np.linspace(2,3,num=50,retstep=True) # step size is auto and that is same for every element(`retstep` gives that)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [74]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

#### Identity Matrix

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])